### ISSUE TITLE
Decode string from  libag3.so

### ISSUE THREAD

**Issue by MrFireFrog** [defnotcat/libag3-c#1]
How we can decode string from  libag3.so

**Comment by caiquepfr** [comment]
I needed this too, did u managed to do?

**Comment by MrFireFrog** [comment]
Nope, i know that he encrypt info about phone

**Comment by defnotcat** [comment]
Hello! I guess you'd have to reverse the whole algorithm.

Why do you need that though? If you're looking to know what's being encrypted to replicate it in your own code you can simply use Frida to hook the native function that makes the encryption happen and thus intercept the content raw.

Here's some hint, this is what's encrypted:

`{"nonce": "1652844431-Hoz2vVEJkGZCcJ6qgLJ9x6nwMfddYMTb", "sig": ["samsung\/on5xelteub\/on5xelte:8.0.0\/R16NW\/G570MUBS5CSD1:user\/release-keys", "13575,1652782883,1652782883", "15861,1652782911,1652782911", "556234"]}` 

`nonce` is the current timestamp and a random string `[A-z0-9]`
`sig` is the device fingerprint followed by some stuff I'll let you figure out

Hope that helps, good luck to you both!

**Comment by MrFireFrog** [comment]
> 

Thank you, everything works. But could you share the Frida script, pls. 
Just all Firda Native Scripts from google crash app, or doesn't work.
Sry for reopen Issues, just am don't know how to write to you

**Comment by defnotcat** [comment]
Hi again!


I don't know if `libag3.so` has had an update since I released this, so I'm not sure whether this offset is still valid, but this is the hook I used to get the JSON before it gets encoded:

```js
var libag3 = Process.findModuleByName('libag3.so');

Interceptor.attach(libag3.base.add(0x211e8), {
    onEnter: function(args) {
        console.log(`[pre_encryption] JSON=${Memory.readCString(args[0])}`)
    },
    onLeave: function() { }
})
```
