### ISSUE TITLE
reverse engineering new ver

### ISSUE THREAD

**Issue by caiquepfr** [defnotcat/libag3-c#4]
Hey, I'm trying to reverse engineer the same things as you did but it's a different version, can you share any tips on how you achieved this result?

**Comment by defnotcat** [comment]
Hey! Frida and Binary Ninja were the primary tools I used to make this.

I started by taking a look at the JNI method (which I found using [jnitrace-engine](https://github.com/chame1eon/jnitrace-engine)) then tracked down the functions it was calling.

Once I identified the functions taking care of the encoding process, I quite literally copy-pasted things from Binary Ninja's High Level IL representation and patched it up in C. But don't get me wrong, it took quite a lot of time to get it right.

Hope that helps at least a little, good luck to you in this project! It's quite some fun (:

**Comment by caiquepfr** [comment]
That actually helps a lot, I've been using Ghidra for decompiling but will check Binary Ninja to see if it helps.
Thanks @defnotcat!
