### ISSUE TITLE
I came across the same decompilation case

### ISSUE THREAD

**Issue by heweizhen0822** [defnotcat/libag3-c#6]
I came across the same decompilation case 。I want you to help me deal with this problem for a fee. I can add your telegram and look forward to your reply

**Comment by defnotcat** [comment]
Hi! Sorry, not interested. I'm happy to answer any question you might have though.

**Comment by heweizhen0822** [comment]
> 你好！抱歉，我不感兴趣。不过我很乐意回答你的任何问题。

I managed to reverse the app and call so through unidbg. But now I have some doubts. The e headers I generated can be used for a while at first and will be all intercepted after about 5 minutes. 403, I guess it is related to a parameter that contains plain and key in the tag. I do not know whether the risk is controlled because these two parameters are not simulated, because I directly obtained these two parameters from so, I do not know how to simulate them, so do you know this thing?

**Comment by defnotcat** [comment]
So If I understand correctly, you're currently manually invoking the `libag3.so` function (the one exposed through the JNI) to obtain the two Base64 strings representing the `tag` field in the final JSON payload, correct?

And you ask what these two strings represent and how to recreate them independently, correct?

The `tag` field contains additional security data that has been encoded into a custom format. The first element is the encoded data itself, and the second the seed or salt used to decode it.

Here's an example of a decoded `tag` field:

```
{"nonce": "1652844431-Hoz2vVEJkGZCcJ6qgLJ9x6nwMfddYMTb", "sig": ["samsung\/on5xelteub\/on5xelte:8.0.0\/R16NW\/G570MUBS5CSD1:user\/release-keys", "13575,1652782883,1652782883", "15861,1652782911,1652782911", "556234"]}
```

To be able to recreate the tag field independently from the `libag3.so` library, you'll need to figure out what the plain data exactly contains and how to generate data that would mimic it, then encode it into the same format.

This repository contains all the code necessary to encode data into this custom format, even though it's old it seemingly still the implementation used by all applications.

Check out the [usage example](https://github.com/defnotcat/libag3-c/blob/master/Usage.cs) for an example on how to use it from within your own code.

Hope that helps. Good luck!

**Comment by heweizhen0822** [comment]
First of all, thank you very much, but this version does not seem to work, now it is eTopV2, before e header was a:xxxxx

Now the e header is b:xxxx, the content I coded with this library cannot pass verification, can you give me your Telegram or Discord? Can I ask you a few details? Maybe I'm using it the wrong way? Thank you again
